echo '2020 on port 8020'
curl -X 'GET' 'http://centos:8020/icd/release/11/mms' -H 'accept: application/json' -H 'API-Version: v2' -H 'Accept-Language: en'
echo ''
echo '2021 on port 8021'
curl -X 'GET' 'http://centos:8021/icd/release/11/mms' -H 'accept: application/json' -H 'API-Version: v2' -H 'Accept-Language: en'
echo ''
echo '2022 on port 8022'
curl -X 'GET' 'http://centos:8022/icd/release/11/mms' -H 'accept: application/json' -H 'API-Version: v2' -H 'Accept-Language: en'
echo ''
echo '2023-01 on port 8023'
curl -X 'GET' 'http://centos:8023/icd/release/11/mms' -H 'accept: application/json' -H 'API-Version: v2' -H 'Accept-Language: en'
echo ''
echo '2024-01 on port 8024'
curl -X 'GET' 'http://centos:8024/icd/release/11/mms' -H 'accept: application/json' -H 'API-Version: v2' -H 'Accept-Language: en'
echo ''
echo '2025-01 on port 8025'
curl -X 'GET' 'http://centos:8025/icd/release/11/mms' -H 'accept: application/json' -H 'API-Version: v2' -H 'Accept-Language: en'
echo ''
